messages:
  flyOn: "&#50ff50Режим полета включен."
  flyOff: "&#50ff50Режим полета отключен."
  removeElytra: "&#50ff50Режим полета отключен! Наденьте элитры."
  noElytra: "&#ee6060Чтобы включить режим полета, требуются элитры!"
  noPerms: "&#ee6060У вас недостаточно прав!"
  onlyPlayes: "&#ff0000Эту команду может выполнить только игрок."